version:  '3.8'
services:
  mysql:
   image: mysql:5.7
   restart: on-failure
   environment:
     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
     MYSQL_DATABASE: ${DB_DATABASE}
  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './:/usr/src/app'
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000