<?php

namespace ContainerXG3A5Dw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PostFormType' shared autowired service.
     *
     * @return \App\Form\PostFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PostFormType.php';

        return $container->privates['App\\Form\\PostFormType'] = new \App\Form\PostFormType();
    }
}
