<?php

namespace ContainerHTQERmW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IX1q_J0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IX1q.J0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IX1q.J0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'guardHandler' => ['privates', 'security.authentication.guard_handler', 'getSecurity_Authentication_GuardHandlerService', true],
        ], [
            'guardHandler' => '?',
        ]);
    }
}
