<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0h0a2Bk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0h0a2Bk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0h0a2Bk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0h0a2Bk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0h0a2Bk\App_KernelDevDebugContainer([
    'container.build_hash' => '0h0a2Bk',
    'container.build_id' => '2bfcb700',
    'container.build_time' => 1612552041,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0h0a2Bk');
