<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXG3A5Dw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXG3A5Dw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXG3A5Dw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXG3A5Dw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXG3A5Dw\App_KernelDevDebugContainer([
    'container.build_hash' => 'XG3A5Dw',
    'container.build_id' => '94fbdd7f',
    'container.build_time' => 1612725758,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXG3A5Dw');
