<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJni97Rl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJni97Rl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJni97Rl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJni97Rl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJni97Rl\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jni97Rl',
    'container.build_id' => '5d3abee2',
    'container.build_time' => 1612566036,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJni97Rl');
